# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

#PreCommit:
#  RuboCop:
#    enabled: true
#    on_warn: fail # Treat all warnings as failures
#
#  TrailingWhitespace:
#    enabled: true
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

CommitMsg:
  CapitalizedSubject:
    enabled: false

PreCommit:
  RuboCop:
    enabled: true
    problem_on_unmodified_line: report # warn about unmodified lines from files in commit
    on_warn: fail # treat all warnings as failures
    command: ["bundle", "exec", "rubocop", "--auto-correct", "--force-exclusion"] # force-exclusion to make sure no matter what it will respect .rubocop.yml
    exclude:
      - ".metrics/**/*"

  LinesAddedMetric:
    enabled: true
    type: script # <— tell Overcommit "this is a Script hook"
    description: "Update .metrics/total_lines_added.txt with cumulative additions"
    required_executable: "bash"
    command:
      - bash
      - scripts/update_lines_added.sh
    modify_index: true # tells Overcommit we will 'git add' inside the hook
    quiet: false
