Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - "db/schema.rb"

Style/WordArray:
  Exclude:
    - "db/schema.rb"

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/SymbolArray:
  Exclude:
    - "config/routes.rb"
    - "db/migrate/**/*.rb"
